services:
  oictcasestudy.api:
    build:
      context: .
      dockerfile: src/OICTCaseStudy.Api/Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: "8080"
    ports:
      - "8080:8080"
